### ISSUE TITLE
Ana 3

### ISSUE THREAD

**Issue by jf2718** [pavelzw/Analysis-II-Skript#36]
Hi, 
ist für dieses Semester ein Ana 3 Skript geplant? Ich wäre auch bereit, was dazu beizutragen

**Comment by pavelzw** [comment]
Hi,
dieses Semester mache ich kein Ana3 Skript. Es gibt jedoch [hier](https://www.overleaf.com/read/fzjndvbjwdpw) ein Ana 3 Skript, welches nicht von mir erstellt wird.

**Comment by jf2718** [comment]
Vielen Dank für den Hinweis.
